### ISSUE TITLE
Add option "Show home/root" in prefix to breadcrumbs

### ISSUE THREAD

**Issue by mgeoffray** [AgrosupDijon-Eduter/BreadcrumbBundle#4]
Hello,

as I understand there is no option to show the "Home"/"root" link when we are on another page.
Example: on contact page the current breadcrumbs is "Contact"
This would be a plus if we can show "Home > Conact"

Is there a way to add this feature easily ?

Thank you.

**Comment by waldo2188** [comment]
Hi !
Check the 2.1.0 version.
I've removed a function that was unnecessary.
Now you can have a root node like you ask.

You can have your `Home` link like this :
```php
        $menu = $factory->createItem('Home', array('route' => '_home'));
        $menu->addChild('Contact', array('route' => '_contact'));
```

I hope that helps.

**Comment by davidromani** [comment]
Hello.

I just updated your vendor from v2.0.2 to v2.1.0 and now I'm getting an unnecessary 'root' link in my breadcrumb. 

Due to this is a legacy project, can I disable (or hide) the 'root' link easily? I need to override your default template to achieve it?

Thx.
